import "dotenv/config";
import express from "express";
import cors from "cors";
import { body, validationResult } from "express-validator";
import { initDb, query } from "./db.js";
import { loginHandler, requireAuth } from "./auth.js";

const app = express();
app.use(cors({
  origin: (process.env.FRONTEND_ORIGIN || "http://localhost:5173").split(",").map(x => x.trim()),
  credentials: false
}));
app.use(express.json({ limit: "5mb" }));

const asyncRoute = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const validate = (req, res, next) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) return res.status(400).json({ error: errors.array()[0].msg, details: errors.array() });
  next();
};

app.get("/api/health", (req, res) => res.json({ ok: true, app: "DIGI Digital Service API" }));
app.post("/api/auth/login", loginHandler);

app.use("/api", requireAuth);

app.get("/api/transactions", asyncRoute(async (req, res) => {
  const { from, to, search } = req.query;
  const params = [];
  const conditions = [];
  if (from) { params.push(from); conditions.push(`transaction_date >= $${params.length}::date`); }
  if (to) { params.push(to); conditions.push(`transaction_date < ($${params.length}::date + INTERVAL '1 day')`); }
  if (search) {
    params.push(`%${String(search).slice(0, 100)}%`);
    conditions.push(`(invoice_no ILIKE $${params.length} OR customer_name ILIKE $${params.length} OR customer_phone ILIKE $${params.length} OR service_name ILIKE $${params.length})`);
  }
  const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";
  const result = await query(`SELECT * FROM transactions ${where} ORDER BY transaction_date DESC LIMIT 500`, params);
  const rows = result.rows.map(r => ({
    ...r,
    items: r.items
      ? (typeof r.items === "string" ? JSON.parse(r.items) : r.items)
      : [{ service_name: r.service_name, description: r.description, quantity: r.quantity, price: r.price }]
  }));
  res.json(rows);
}));

app.post("/api/transactions", [
  body("customer_name").optional().trim().isLength({ max: 150 }),
  body("service_charge").optional().isFloat({ min: 0 }).withMessage("Service charge must be zero or more."),
  body("discount").optional().isFloat({ min: 0 }).withMessage("Discount must be zero or more."),
  body("payment_method").isIn(["Cash", "eSewa", "Khalti", "Bank", "Other"]).withMessage("Choose a valid payment method.")
], validate, asyncRoute(async (req, res) => {
  const b = req.body;
  
  // Normalize items array
  let items = Array.isArray(b.items) && b.items.length > 0 ? b.items : null;
  if (!items && b.service_name) {
    items = [{
      service_name: b.service_name,
      description: b.description || "",
      quantity: Number(b.quantity || 1),
      price: Number(b.price || 0)
    }];
  }

  if (!items || items.length === 0) {
    return res.status(400).json({ error: "At least one service item is required." });
  }

  // Validate each service item
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    if (!item.service_name || !item.service_name.trim()) {
      return res.status(400).json({ error: `Service item #${i + 1} must have a name.` });
    }
    const q = Number(item.quantity);
    if (!q || q <= 0) {
      return res.status(400).json({ error: `Quantity for '${item.service_name}' must be at least 1.` });
    }
    const p = Number(item.price);
    if (isNaN(p) || p < 0) {
      return res.status(400).json({ error: `Price for '${item.service_name}' cannot be negative.` });
    }
    item.quantity = q;
    item.price = p;
    item.service_name = item.service_name.trim();
    item.description = (item.description || "").trim() || null;
  }

  const subtotal = items.reduce((sum, item) => sum + (item.quantity * item.price), 0);
  const charge = Number(b.service_charge || 0);
  const discount = Number(b.discount || 0);
  if (discount > subtotal + charge) {
    return res.status(400).json({ error: "Discount cannot exceed subtotal plus service charge." });
  }
  const total = Number((subtotal + charge - discount).toFixed(2));

  const summaryServiceName = items.map(i => i.service_name).join(", ");
  const summaryDescription = items.map(i => i.description).filter(Boolean).join("; ") || null;
  const totalQuantity = items.reduce((sum, i) => sum + i.quantity, 0);
  const averagePrice = Number((subtotal / (totalQuantity || 1)).toFixed(2));

  // Atomic invoice sequence is generated by PostgreSQL sequence to avoid duplicate invoice numbers.
  const inserted = await query(`
    INSERT INTO transactions
      (invoice_no, customer_name, customer_phone, service_name, description, quantity, price, service_charge, discount, total, payment_method, payment_status, transaction_date, items)
    VALUES
      ('TEMP-' || nextval(pg_get_serial_sequence('transactions','id')), $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,COALESCE($12::timestamptz,NOW()), $13)
    RETURNING *
  `, [
    (b.customer_name || "").trim() || "Walk-in Customer",
    (b.customer_phone || "").trim() || null,
    summaryServiceName,
    summaryDescription,
    totalQuantity,
    averagePrice,
    charge,
    discount,
    total,
    b.payment_method,
    b.payment_status === "Pending" ? "Pending" : "Paid",
    b.transaction_date || null,
    JSON.stringify(items)
  ]);
  const row = inserted.rows[0];
  const year = new Date(row.transaction_date).getFullYear();
  const invoiceNo = `DIGI-${year}-${String(row.id).padStart(6, "0")}`;
  const updated = await query("UPDATE transactions SET invoice_no=$1 WHERE id=$2 RETURNING *", [invoiceNo, row.id]);
  const updatedRow = updated.rows[0];
  updatedRow.items = items;
  res.status(201).json(updatedRow);
}));

app.get("/api/expenses", asyncRoute(async (req, res) => {
  const result = await query("SELECT * FROM expenses ORDER BY expense_date DESC, id DESC LIMIT 500");
  res.json(result.rows);
}));

app.post("/api/expenses", [
  body("title").trim().isLength({ min: 1, max: 150 }).withMessage("Expense title is required."),
  body("amount").isFloat({ gt: 0 }).withMessage("Expense amount must be greater than zero.")
], validate, asyncRoute(async (req, res) => {
  const b = req.body;
  const result = await query(
    "INSERT INTO expenses (title,category,amount,note,expense_date) VALUES ($1,$2,$3,$4,COALESCE($5::date,CURRENT_DATE)) RETURNING *",
    [b.title.trim(), (b.category || "Other").trim(), Number(b.amount), (b.note || "").trim() || null, b.expense_date || null]
  );
  res.status(201).json(result.rows[0]);
}));

app.patch("/api/transactions/:id/payment", [
  body("payment_status").isIn(["Paid", "Pending"]).withMessage("Payment status must be Paid or Pending."),
  body("payment_method").optional().isIn(["Cash", "eSewa", "Khalti", "Bank", "Other"]).withMessage("Invalid payment method.")
], validate, asyncRoute(async (req, res) => {
  if (!/^\d+$/.test(req.params.id)) return res.status(400).json({ error: "Invalid transaction ID." });
  const { payment_status, payment_method } = req.body;
  const updates = ["payment_status = $1"];
  const params = [payment_status];
  if (payment_method) {
    params.push(payment_method);
    updates.push(`payment_method = $${params.length}`);
  }
  params.push(req.params.id);
  const result = await query(
    `UPDATE transactions SET ${updates.join(", ")} WHERE id = $${params.length} RETURNING *`,
    params
  );
  if (!result.rows.length) return res.status(404).json({ error: "Transaction not found." });
  res.json(result.rows[0]);
}));

app.delete("/api/transactions/:id", asyncRoute(async (req, res) => {
  if (!/^\d+$/.test(req.params.id)) return res.status(400).json({ error: "Invalid transaction ID." });
  await query("DELETE FROM transactions WHERE id=$1", [req.params.id]);
  res.status(204).end();
}));

app.get("/api/settings", asyncRoute(async (req, res) => {
  const result = await query("SELECT value FROM settings WHERE key = 'shop_profile'");
  if (result.rows.length > 0) {
    const val = result.rows[0].value;
    return res.json(typeof val === "string" ? JSON.parse(val) : val);
  }
  res.json({
    shop_name: "DIGI DIGITAL SERVICE",
    pan_number: "",
    mobile_number: "",
    address: "",
    tagline: "Digital & Online Service Center",
    footer_note: "Thank you for your visit!",
    default_format: "thermal",
    logo_url: ""
  });
}));

app.post("/api/settings", asyncRoute(async (req, res) => {
  const b = req.body || {};
  const settingsData = {
    shop_name: (b.shop_name || "DIGI DIGITAL SERVICE").trim(),
    pan_number: (b.pan_number || "").trim(),
    mobile_number: (b.mobile_number || "").trim(),
    address: (b.address || "").trim(),
    tagline: (b.tagline || "Digital & Online Service Center").trim(),
    footer_note: (b.footer_note || "Thank you for your visit!").trim(),
    default_format: b.default_format === "a4" ? "a4" : "thermal",
    logo_url: b.logo_url || ""
  };
  await query(
    `INSERT INTO settings (key, value, updated_at)
     VALUES ('shop_profile', $1, NOW())
     ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`,
    [JSON.stringify(settingsData)]
  );
  res.json(settingsData);
}));

app.get("/api/reports/summary", asyncRoute(async (req, res) => {
  const { from, to } = req.query;
  const start = from || new Date().toISOString().slice(0,10);
  const end = to || start;
  const sales = await query(`
    SELECT COUNT(*)::int AS transaction_count,
      COALESCE(SUM(total),0)::numeric(12,2) AS total_sales,
      COALESCE(SUM(CASE WHEN payment_method='Cash' THEN total ELSE 0 END),0)::numeric(12,2) AS cash_total,
      COALESCE(SUM(CASE WHEN payment_method<>'Cash' THEN total ELSE 0 END),0)::numeric(12,2) AS online_total
    FROM transactions WHERE transaction_date >= $1::date AND transaction_date < ($2::date + INTERVAL '1 day')
  `, [start, end]);
  const expenses = await query(`
    SELECT COALESCE(SUM(amount),0)::numeric(12,2) AS total_expenses
    FROM expenses WHERE expense_date >= $1::date AND expense_date <= $2::date
  `, [start, end]);
  const s = sales.rows[0], e = expenses.rows[0];
  res.json({ ...s, total_expenses: e.total_expenses, net_after_expenses: Number(s.total_sales) - Number(e.total_expenses), from: start, to: end });
}));

app.use((err, req, res, next) => {
  console.error(err);
  res.status(500).json({ error: "Something went wrong. Check backend logs and database configuration." });
});

const port = Number(process.env.PORT || 5000);
initDb().then(() => app.listen(port, () => console.log(`DIGI API listening on ${port}`)))
  .catch(err => { console.error("Database initialization failed:", err.message); process.exit(1); });
